server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true
  
  # 企业邮箱
  mail:
    host: smtp.exmail.qq.com
    username: xxx
    password: xxx
    default-encoding: UTF-8
    smtp:
      auth: true
      starttls:
        enable: false
        required: false

mybatis-plus:
  type-aliases-package: cc.mrbird.febs.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty

logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error
febs:
  active: ${spring.profiles.active}